### ISSUE TITLE
How to get the rl_model.pth'

### ISSUE THREAD

**Issue by guchi-ac** [sarapohland/stranger-danger#1]
Thank you for the great work ，I'm having some problems running **1.1) Collect pedestrian walking data**,
`FileNotFoundError: [Errno 2] No such file or directory: '../crowd_sim/envs/policy/cadrl/rl_model.pth'`
 I understand that this is a cadrl weight file that needs to be trained, but I don't know how to set the training parameters for training cadrl strategies, will the setting of the parameters affect the final effect?
I would appreciate it if you could provide a weight file or a parameter design for the training。

**Comment by sarapohland** [comment]
Thanks for pointing out this oversight! We just added the model weights file for the CADRL policy we were using. Please let us know if the issue persists or if you notice any other errors!
